BookListMVC/Models/Entity/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Tickets.Models.Abstractions;

namespace Tickets.Models
{
    public class Ticket : IEntity<int>
    {
        [Key]
        public int Id { get; set; }


        [StringLength(50)]
        public string PersonName { get; set; }

        [StringLength(50)]
        [Required]
        public string Email { get; set; }  
        
        [StringLength(13)]
        [Required]
        public string Phone { get; set; }    

        [StringLength(16)]
        [Required]
        public string CreditCard { get; set; }
        
        public int PerfId { get; set; }
        [StringLength(50)]

        public string PerfName { get; set; }

        [DataType("datetime()")]
        public DateTime PerfDate { get; set; }

        [DataType("money")]
        public decimal PerfPrice { get; set; }

        [DefaultValue(false)]
        public bool IsConfirmed { get; set; }



        public  Performance  PPerformanceName { get; set; }
        public  Performance  PPerformanceId { get; set; }
        public  Performance  PPerformancePrice { get; set; }
        public  Performance  PPerformanceDate { get; set; }

    }
}

BookListMVC/Controllers/PerfListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookListMVC.Models;
using Tickets.Models;
using Tickets.BusinessLogic.Abstracrions;

namespace Tickets.Controllers
{
    public class PerfListController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IPerformanceService _service;
        

        public PerfListController(ApplicationDbContext context, IPerformanceService service)
        {
            _context = context;
            _service = service;
        }

        // GET: PerfList
        public async Task<IActionResult> Index()
        {
            return View(await _context.Performances.ToListAsync());
        }

        // GET: PerfList/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performances
                .FirstOrDefaultAsync(m => m.Id == id);
            if (performance == null)
            {
                return NotFound();
            }

            return View(performance);
        }

        // GET: PerfList/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PerfList/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Venue,Date,SeatsCount,Price,Info")] Performance performance)
        {
            if (ModelState.IsValid)
            {
               await  _service.CreateAsync(performance);
                //_context.Add(performance);
                //await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(performance);
        }

        // GET: PerfList/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performances.FindAsync(id);
            if (performance == null)
            {
                return NotFound();
            }
            return View(performance);
        }

        // POST: PerfList/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Venue,Date,SeatsCount,Price,Info")] Performance performance)
        {
            if (id != performance.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(performance);
                  //  await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PerformanceExists(performance.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(performance);
        }

        // GET: PerfList/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performances
                .FirstOrDefaultAsync(m => m.Id == id);
            if (performance == null)
            {
                return NotFound();
            }

            return View(performance);
        }

        // POST: PerfList/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var performance = await _context.Performances.FindAsync(id);
            await _service.DeleteAsync(id);
            //_context.Performances.Remove(performance);
            //await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PerformanceExists(int id)
        {
            return _context.Performances.Any(e => e.Id == id);
        }


        #region API Calls
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _context.Performances.ToListAsync() });
        }

       
        #endregion
    }
}

BookListMVC/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookListMVC.Models;
using Tickets.Models;
using Tickets.BusinessLogic.Abstracrions;

namespace Tickets.Controllers
{
    public class TicketsController : Controller
    {
       public Performance Performance { get; set; }
        [BindProperty]
        public  Ticket Ticket { get; set; }
        private readonly ApplicationDbContext _context;
        private readonly ITicketService _service;

        public TicketsController(ApplicationDbContext context, ITicketService service)
        {
            _context = context;
            _service = service;
        }

        // GET: Tickets
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Tickets.Include(t => t.PPerformanceName).Include(t => t.PPerformanceName).Include(t => t.PPerformanceName).Include(t => t.PPerformanceName);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        public async Task<IActionResult> Create(int? id)
        {
            var perf = await _context.Performances.FindAsync(id);
            

            if ( perf.Id != id)
                {
                    return NotFound();
                }


            Ticket t = new Ticket
            {

                PerfId = perf.Id,
                PerfName = perf.Name,
                PerfPrice = perf.Price,
                PerfDate = perf.Date
            };
            

            return View(t);
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PersonName,Email,Phone,CreditCard,PerfId,PerfName,PerfDate,PerfPrice,IsConfirmed")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ticket);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PersonName,Email,Phone,CreditCard,PerfId,PerfName,PerfDate,PerfPrice,IsConfirmed")] Ticket ticket)
        {

            if (id != ticket.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(ticket);
                   // await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketExists(ticket.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                //.Include(t => t.PPerformanceDate)//.ThenInclude(u => u.TPerfDates)
               // .Include(t => t.PPerformanceId)//.ThenInclude(u => u.TPerfIds)
                .Include(t => t.PPerformanceName)//.ThenInclude(u => u.TPerfNames)
                //.Include(t => t.PPerformancePrice)//.ThenInclude(u => u.TPerfPrices)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {



            var result = await _service.DeleteAsync(id);
           /* return Ok();// insertedItem;

            var ticket = await _context.Tickets.FindAsync(id);
            if(ticket == null)
            {
                return null;
            }
            _context.Tickets.Remove(ticket);
            await _context.SaveChangesAsync();*/
            return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(int id)
        {
            return _context.Tickets.Any(e => e.Id == id);
        }
    }
}

BookListMVC/Views/Tickets/Create.cshtml
@model Tickets.Models.Ticket

@{
    ViewData["Title"] = "Tickets";
}

<h1>Buy Ticket</h1>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" >
            @if (Model.Id != 0)
            {
        <input type="hidden" asp-for="Id" />
        }
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                   <div class="form-group">
                <label asp-for="@Model.PersonName" class="control-label"></label>
                <input asp-for="@Model.PersonName" class="form-control" />
                <span asp-validation-for="@Model.PersonName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Email" class="control-label"></label>
                <input asp-for="@Model.Email" class="form-control" />
                <span asp-validation-for="@Model.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Phone" class="control-label"></label>
                <input asp-for="@Model.Phone" class="form-control" />
                <span asp-validation-for="@Model.Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.CreditCard" class="control-label"></label>
                <input asp-for="@Model.CreditCard" class="form-control" />
                <span asp-validation-for="@Model.CreditCard" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PerfId" class="control-label"></label>
                <input asp-for="PerfId" class="form-control"  readonly/>
                <span asp-validation-for="PerfId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.PerfName" class="control-label"></label>
                <input asp-for="@Model.PerfName" class="form-control"  readonly/>
                <span asp-validation-for="@Model.PerfName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.PerfDate" class="control-label"></label>
                <input asp-for="@Model.PerfDate" class="form-control" readonly />
                <span asp-validation-for="@Model.PerfDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.PerfPrice" class="control-label"></label>
                <input asp-for="@Model.PerfPrice" class="form-control" readonly />
                <span asp-validation-for="@Model.PerfPrice" class="text-danger"></span>
            </div>
@*            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsConfirmed" /> @Html.DisplayNameFor(model => model.IsConfirmed)
                </label>
            </div>*@
            <div class="form-group">
                <input type="submit" value=" Buy " class="btn btn-success form-control" asp-action="Create"  />
            </div>
        </form>
    </div>
</div>
@*asp-controller="PerfList"*@
<div>
    <a asp-action="Index" >Back to Performances</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookListMVC/Views/Tickets/Delete.cshtml
@model Tickets.Models.Ticket

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2"> 
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreditCard)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreditCard)
        </dd> 
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsConfirmed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsConfirmed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PerfName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PerfName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PerfId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PerfId)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PerfPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PerfPrice)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PerfDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PerfDate)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookListMVC/Views/Tickets/Details.cshtml
@model Tickets.Models.Ticket

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreditCard)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreditCard)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsConfirmed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsConfirmed)
        </dd>
        <dt class = "col-sm-2">
           Name @*@Html.DisplayNameFor(model => model.PPerformanceName)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PPerformanceName.Name)
        </dd>
        <dt class = "col-sm-2">
           Id@* @Html.DisplayNameFor(model => model.PPerformanceId)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PPerformanceName.Id)
        </dd>
        <dt class = "col-sm-2">
            Price@*@Html.DisplayNameFor(model => model.PPerformancePrice)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PPerformanceName.Price)
        </dd>
        <dt class = "col-sm-2">
           Date@* @Html.DisplayNameFor(model => model.PPerformanceDate)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PPerformanceName.Date)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BookListMVC/Views/Tickets/Edit.cshtml
@model Tickets.Models.Ticket

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PersonName" class="control-label"></label>
                <input asp-for="PersonName" class="form-control" />
                <span asp-validation-for="PersonName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreditCard" class="control-label"></label>
                <input asp-for="CreditCard" class="form-control" />
                <span asp-validation-for="CreditCard" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PerfId" class="control-label"></label>
                @*<select asp-for="PerfId" class="form-control" asp-items="ViewBag.Tickets"></select>*@
                <input asp-for="PerfId" class="form-control" readonly/>
                <span asp-validation-for="PerfId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PerfName" class="control-label"></label>
                <input asp-for="PerfName" class="form-control" readonly/>
                <span asp-validation-for="PerfName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PerfDate" class="control-label"></label>
                <input asp-for="PerfDate" class="form-control" readonly/>
                <span asp-validation-for="PerfDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PerfPrice" class="control-label"></label>
                <input asp-for="PerfPrice" class="form-control" readonly/>
                <span asp-validation-for="PerfPrice" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsConfirmed" /> @Html.DisplayNameFor(model => model.IsConfirmed)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookListMVC/Views/Tickets/Index.cshtml
@model IEnumerable<Tickets.Models.Ticket>

@{
    ViewData["Title"] = "Index";
    
}

<h1>Recently bought tickets</h1>
 
<table class="table">
    <thead>
        <tr>
            <th>
                Person@*@Html.DisplayNameFor(model => model.PersonName)*@
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreditCard)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsConfirmed)
            </th>
            <th>
                Name@*@Html.DisplayNameFor(model => model.PPerformanceName)*@
            </th>
            <th>
                Id @* @Html.DisplayNameFor(model => model.PPerformanceId)*@
            </th>
            <th>
                Price@*@Html.DisplayNameFor(model => model.PPerformancePrice)*@
            </th>
            <th>
                Date@*@Html.DisplayNameFor(model => model.PPerformanceDate)*@
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PersonName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreditCard)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsConfirmed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PPerformanceName.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PPerformanceId.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PPerformancePrice.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PPerformanceDate.Date)
            </td>
            <td>
                <a asp-action="Edit" asp-controller="Tickets" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-controller="Tickets" asp-route-id="@item.Id">Details</a> | 
                <a asp-action="Delete" asp-controller="Tickets" asp-route-id="@item.Id">Delete</a> |
            </td>
        </tr>
}
    </tbody>
</table>
<script>
    function Delete(url) {
        swal({
            title: "Are you sure?",
            text: "Once deleted, you will not be able to recover",
            icon: "warning",
            buttons: true,
            dangerMode: true
        }).then((willDelete) => {
            if (willDelete) {
                $.ajax({
                    type: "DELETE",
                    url: url,
                    success: function (data) {
                        if (data.success) {
                            toastr.success(data.message);
                            dataTable.ajax.reload();
                        }
                        else {
                            toastr.error(data.message);
                        }
                    }
                });
            }
        });
</script>