BookListMVC/Controllers/PerformancesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookListMVC.Models;
using Tickets.Models;
using Tickets.BusinessLogic.Abstracrions;

namespace Tickets.Controllers
{
    public class PerformancesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IPerformanceService _service;

        public PerformancesController(ApplicationDbContext context, IPerformanceService service)
        {
            _context = context;
            _service = service;
        }

        // GET: Performances
        public async Task<IActionResult> Index()
        {
            return View(await _context.Performances.ToListAsync());
        }

        // GET: Performances/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performances
                .FirstOrDefaultAsync(m => m.Id == id);
            if (performance == null)
            {
                return NotFound();
            }

            return View(performance);
        }

        // GET: Performances/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Performances/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Venue,Date,SeatsCount,Price,Info")] Performance performance)
        {
            if (ModelState.IsValid)
            {
               await  _service.CreateAsync(performance);
               // _context.Add(performance);
                //await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(performance);
        }

        // GET: Performances/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performances.FindAsync(id);
            if (performance == null)
            {
                return NotFound();
            }
            return View(performance);
        }

        // POST: Performances/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Venue,Date,SeatsCount,Price,Info")] Performance performance)
        {
            if (id != performance.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   await _service.UpdateAsync(performance);
                  //  await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PerformanceExists(performance.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(performance);
        }

        // GET: Performances/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performances
                .FirstOrDefaultAsync(m => m.Id == id);
            if (performance == null)
            {
                return NotFound();
            }

            return View(performance);
        }

        // POST: Performances/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var performance = await _context.Performances.FindAsync(id);
            await _service.DeleteAsync(id);
           // _context.Performances.Remove(performance);
            //await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PerformanceExists(int id)
        {
            return _context.Performances.Any(e => e.Id == id);
        }
    }
}

BookListMVC/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookListMVC.Models;
using Tickets.Models;
using Tickets.BusinessLogic.Abstracrions;

namespace Tickets.Controllers
{
    public class TicketsController : Controller
    {
       public Performance Performance { get; set; }
        [BindProperty]
        public  Ticket Ticket { get; set; }
        private readonly ApplicationDbContext _context;
        private readonly ITicketService _service;

        public TicketsController(ApplicationDbContext context, ITicketService service)
        {
            _context = context;
            _service = service;
        }

        // GET: Tickets
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Tickets.Include(t => t.PPerformanceName).Include(t => t.PPerformanceName).Include(t => t.PPerformanceName).Include(t => t.PPerformanceName);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        public async Task<IActionResult> Create(int? id)
        {
            var perf = await _context.Performances.FindAsync(id);
            

            if ( perf.Id != id)
                {
                    return NotFound();
                }


            Ticket t = new Ticket
            {

                PerfId = perf.Id,
                PerfName = perf.Name,
                PerfPrice = perf.Price,
                PerfDate = perf.Date
            };
            

            return View(t);
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PersonName,Email,Phone,CreditCard,PerfId,PerfName,PerfDate,PerfPrice,IsConfirmed")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ticket);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PersonName,Email,Phone,CreditCard,PerfId,PerfName,PerfDate,PerfPrice,IsConfirmed")] Ticket ticket)
        {

            if (id != ticket.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.UpdateAsync(ticket);
                   // await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketExists(ticket.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                //.Include(t => t.PPerformanceDate)//.ThenInclude(u => u.TPerfDates)
               // .Include(t => t.PPerformanceId)//.ThenInclude(u => u.TPerfIds)
                .Include(t => t.PPerformanceName)//.ThenInclude(u => u.TPerfNames)
                //.Include(t => t.PPerformancePrice)//.ThenInclude(u => u.TPerfPrices)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {



            var result = await _service.DeleteAsync(id);
           /* return Ok();// insertedItem;

            var ticket = await _context.Tickets.FindAsync(id);
            if(ticket == null)
            {
                return null;
            }
            _context.Tickets.Remove(ticket);
            await _context.SaveChangesAsync();*/
            return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(int id)
        {
            return _context.Tickets.Any(e => e.Id == id);
        }
    }
}

BookListMVC/Views/Admins/Create.cshtml
@model Tickets.Models.Admin

@{
    ViewData["Title"] = "Authorisation";
}

<h1>Authorisation</h1>

<h4>Admin</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input name="login" asp-for="Login" class="form-control" />
                <span  asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input autocomplete="off" type="password" name="password" asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-action="Create" type="submit" value="Log in" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Home">Back</a>
</div>

@section Scripts {
    <script src="~/js/authorisation.js"></script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

BookListMVC/Views/Admins/Delete.cshtml
@model Tickets.Models.Admin

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Admin</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Login)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Login)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookListMVC/Views/Admins/Details.cshtml
@model Tickets.Models.Admin

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Admin</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Login)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Login)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BookListMVC/Views/Admins/Edit.cshtml
@model Tickets.Models.Admin

@{
    ViewData["Title"] = "Authorisation";
}

<h1>Authorisation</h1>

<h4>Admin</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger" ></span>
            </div>
            <div class="form-group">
                <input asp-action="Index" type="submit" value="Log in" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookListMVC/Views/Admins/Index.cshtml
@model IEnumerable<Tickets.Models.Admin>

@{
    ViewData["Title"] = "Index";
}

<h1>Admin</h1>


<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
    <form >
        <div>
            <a asp-area="" asp-controller="Tickets" asp-action="Index" class="btn btn-success form-control">View Tickets</a>
        </div>
        <br />
        <div>
            <a class="btn btn-success form-control" asp-controller="Performances" asp-action="Index">Add Performances</a>
        </div>
    </form>
      
 
    </div>